apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reading-list-ingress
  labels:
    app: reading-list
spec:
  ingressClassName: nginx
  rules:
  - host: reading-list.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reading-list-service
            port:
              number: 80

